In [1]:
import pandas as pd
import numpy as np 
import pylab as P 
# Import the module for plotting
import matplotlib.pyplot as plt
from pandas import Series,DataFrame,merge
plt.style.use('ggplot')

# Import daily data

In [2]:
# data import
dailyData = pd.read_csv('../data/csv/stocktwits_twitter_withretweets_daily.csv')
dailyData.head()

,SOURCE,SYMBOL,TIMESTAMP_UTC,BULLISH_INTENSITY,BEARISH_INTENSITY,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,BEAR_SCORED_MESSAGES,BULL_BEAR_MSG_RATIO,TOTAL_SCANNED_MESSAGES
0,stocktwits+twitter_withretweets,10GEN,2011-04-08T04:00:00Z,0,0,0,0,0,0,2
1,stocktwits+twitter_withretweets,10GEN,2011-04-16T04:00:00Z,0,0,0,0,0,0,3
2,stocktwits+twitter_withretweets,10GEN,2011-04-17T04:00:00Z,0,0,0,0,0,0,2
3,stocktwits+twitter_withretweets,10GEN,2011-04-20T04:00:00Z,0,0,0,0,0,0,1
4,stocktwits+twitter_withretweets,10GEN,2011-07-19T04:00:00Z,0,0,0,0,0,0,3

In [3]:
dailyData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7120506 entries, 0 to 7120505
Data columns (total 10 columns):
SOURCE                    object
SYMBOL                    object
TIMESTAMP_UTC             object
BULLISH_INTENSITY         float64
BEARISH_INTENSITY         float64
BULL_MINUS_BEAR           float64
BULL_SCORED_MESSAGES      int64
BEAR_SCORED_MESSAGES      int64
BULL_BEAR_MSG_RATIO       float64
TOTAL_SCANNED_MESSAGES    int64
dtypes: float64(4), int64(3), object(3)
memory usage: 597.6+ MB

# Import symbols

In [4]:
# symbols import
symbols = pd.read_csv('../data/csv/symbology.csv')
symbols.head()

,exchange,symbol,sector,industry,title,all_scanned_January_2016_avg_daily,all_scored_January_2016_avg_daily,stocktwits_scanned_January_2016_avg_daily,stocktwits_scored_January_2016_avg_daily,twitter_scanned_January_2016_avg_daily,...,stocktwits_scanned_2012_avg_monthly,stocktwits_scored_2012_avg_monthly,twitter_scanned_2012_avg_monthly,twitter_scored_2012_avg_monthly,all_scanned_2011_avg_monthly,all_scored_2011_avg_monthly,stocktwits_scanned_2011_avg_monthly,stocktwits_scored_2011_avg_monthly,twitter_scanned_2011_avg_monthly,twitter_scored_2011_avg_monthly
0,NaN,CGC.CA,NaN,NaN,Canopy Growth Corp,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,1KM,NaN,NaN,1000 Markets,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,1RIOT,NaN,NaN,OneRiot,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,500HAT,NaN,NaN,500 Hats,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,56COM,NaN,NaN,56.com,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
symbols.dtypes

exchange                                     object
symbol                                       object
sector                                       object
industry                                     object
title                                        object
all_scanned_January_2016_avg_daily            int64
all_scored_January_2016_avg_daily             int64
stocktwits_scanned_January_2016_avg_daily     int64
stocktwits_scored_January_2016_avg_daily      int64
twitter_scanned_January_2016_avg_daily        int64
twitter_scored_January_2016_avg_daily         int64
all_scanned_YTD_avg_monthly                   int64
all_scored_YTD_avg_monthly                    int64
stocktwits_scanned_YTD_avg_monthly            int64
stocktwits_scored_YTD_avg_monthly             int64
twitter_scanned_YTD_avg_monthly               int64
twitter_scored_YTD_avg_monthly                int64
all_scanned_2015_avg_monthly                  int64
all_scored_2015_avg_monthly                   int64
stocktwits_scanned_2015_avg_monthly           int64
stocktwits_scored_2015_avg_monthly            int64
twitter_scanned_2015_avg_monthly              int64
twitter_scored_2015_avg_monthly               int64
all_scanned_2014_avg_monthly                  int64
all_scored_2014_avg_monthly                   int64
stocktwits_scanned_2014_avg_monthly           int64
stocktwits_scored_2014_avg_monthly            int64
twitter_scanned_2014_avg_monthly              int64
twitter_scored_2014_avg_monthly               int64
all_scanned_2013_avg_monthly                  int64
all_scored_2013_avg_monthly                   int64
stocktwits_scanned_2013_avg_monthly           int64
stocktwits_scored_2013_avg_monthly            int64
twitter_scanned_2013_avg_monthly              int64
twitter_scored_2013_avg_monthly               int64
all_scanned_2012_avg_monthly                  int64
all_scored_2012_avg_monthly                   int64
stocktwits_scanned_2012_avg_monthly           int64
stocktwits_scored_2012_avg_monthly            int64
twitter_scanned_2012_avg_monthly              int64
twitter_scored_2012_avg_monthly               int64
all_scanned_2011_avg_monthly                  int64
all_scored_2011_avg_monthly                   int64
stocktwits_scanned_2011_avg_monthly           int64
stocktwits_scored_2011_avg_monthly            int64
twitter_scanned_2011_avg_monthly              int64
twitter_scored_2011_avg_monthly               int64
dtype: object

In [6]:
symbols.describe()

,all_scanned_January_2016_avg_daily,all_scored_January_2016_avg_daily,stocktwits_scanned_January_2016_avg_daily,stocktwits_scored_January_2016_avg_daily,twitter_scanned_January_2016_avg_daily,twitter_scored_January_2016_avg_daily,all_scanned_YTD_avg_monthly,all_scored_YTD_avg_monthly,stocktwits_scanned_YTD_avg_monthly,stocktwits_scored_YTD_avg_monthly,...,stocktwits_scanned_2012_avg_monthly,stocktwits_scored_2012_avg_monthly,twitter_scanned_2012_avg_monthly,twitter_scored_2012_avg_monthly,all_scanned_2011_avg_monthly,all_scored_2011_avg_monthly,stocktwits_scanned_2011_avg_monthly,stocktwits_scored_2011_avg_monthly,twitter_scanned_2011_avg_monthly,twitter_scored_2011_avg_monthly
count,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444,11444,11444,11444,...,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000
mean,10.797711,2.623733,2.596295,0.857917,7.971077,1.628364,0,0,0,0,...,18.762670,7.893219,68.164191,17.313352,52.076809,15.801468,9.329605,3.837207,42.524467,11.800856
std,77.531277,22.923606,30.250212,11.305452,55.201571,14.682406,0,0,0,0,...,344.342513,148.597889,626.635983,205.135724,462.841925,172.014389,126.386320,52.584767,348.485672,125.595997
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,15.000000,1.000000,2.000000,0.000000,0.000000,0.000000,2.000000,0.000000
75%,5.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0,0,0,0,...,3.000000,1.000000,35.000000,6.000000,21.000000,4.000000,2.000000,0.000000,18.000000,3.000000
max,4281.000000,1256.000000,1691.000000,590.000000,2891.000000,884.000000,0,0,0,0,...,31590.000000,13871.000000,48410.000000,14679.000000,27017.000000,9502.000000,7804.000000,3074.000000,20532.000000,8269.000000

In [7]:
# PLOT A SAMPLE: TOTAL SCANNED MESSAGES BETWEEN 1 TO 11
# dailyData['TOTAL_SCANNED_MESSAGES'].hist(range=(1,10))
# P.show()

# the histogram of the data
plt.hist(dailyData['TOTAL_SCANNED_MESSAGES'], range=[1, 10])
plt.xlabel('Number of Daily Messages')
plt.ylabel('Total Counts')
plt.grid(True)
plt.show()

In [8]:
# plt.show(dailyData.plot(kind = 'box'))

In [9]:
# merge dataset left join
dailySymbol = merge(dailyData,symbols,left_on='SYMBOL',right_on = 'symbol',how = "left")

In [10]:
dailySymbol = dailySymbol.ix[:,1:11]
dailySymbol.columns

Index([u'SYMBOL', u'TIMESTAMP_UTC', u'BULLISH_INTENSITY', u'BEARISH_INTENSITY',
       u'BULL_MINUS_BEAR', u'BULL_SCORED_MESSAGES', u'BEAR_SCORED_MESSAGES',
       u'BULL_BEAR_MSG_RATIO', u'TOTAL_SCANNED_MESSAGES', u'exchange'],
      dtype='object')

In [11]:
# Group By Stock Exchange
companyGrouped = dailySymbol.groupby(dailySymbol['SYMBOL'])
sumByCompany = companyGrouped.sum()
print(sumByCompany.columns)
# sumByExchange

Index([u'BULLISH_INTENSITY', u'BEARISH_INTENSITY', u'BULL_MINUS_BEAR',
       u'BULL_SCORED_MESSAGES', u'BEAR_SCORED_MESSAGES',
       u'BULL_BEAR_MSG_RATIO', u'TOTAL_SCANNED_MESSAGES'],
      dtype='object')

In [12]:
# statistic description for bull bear messages ratio by exchanges
statByCompany_Ratio = companyGrouped['BULL_BEAR_MSG_RATIO'].describe()
statByCompany = companyGrouped.describe()
# export the statistic description by exchanges
statByCompany.to_csv('../data/output/statByCompany.csv', encoding='utf-8')

In [17]:
# a table only contains the total quality of bullish, bearish and total messages for each exchange
messagesTable = sumByCompany.ix[:,[3,4,6]]
messagesTableSorted = messagesTable.sort('TOTAL_SCANNED_MESSAGES', ascending=False)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()

In [18]:
messagesTableSorted.head(25)

,BULL_SCORED_MESSAGES,BEAR_SCORED_MESSAGES,TOTAL_SCANNED_MESSAGES
SYMBOL,,,
MARKET,16728356,8924939,96389673
SP500,9129743,4190486,54079643
TECHNOLOGY,4161229,1946522,22992120
FINANCIAL,3456303,1884489,22676183
SERVICES,2313625,1034138,14597594
HEALTHCARE,1976959,775193,10437364
BASIC_MATERIALS,1410322,551744,8208982
CONSUMER_GOODS,1010060,425071,6010415
INDUSTRIAL_GOODS,552323,209388,5185790
AAPL,880890,519740,4616061
SPY,654165,465827,3146593
AP,40010,16977,2115709
FB,315576,154990,1641991
EURUSD,341587,350623,1554327
UTILITIES,134091,43007,1287902
SPX,269023,189098,1225937
ES_F,225130,207174,1139647
GOOG,173229,74705,1070324
TWTR,179713,91494,995293
TSLA,175345,112664,917347
NFLX,165530,112302,843009
AMZN,159706,73264,826710
PS_OIL,119102,99863,671177
QQQ,126655,90058,654196
GLD,120295,75043,639233

In [20]:
messagesTableSorted.tail(25)

           BULL_SCORED_MESSAGES  BEAR_SCORED_MESSAGES  TOTAL_SCANNED_MESSAGES
SYMBOL
FZP.UN.CA                     0                     0                       1
TIL.UN.CA                     0                     0                       1
ALRTL                         0                     0                       1
GNIUS                         0                     0                       1
MDCTH                         0                     0                       1
HELIO                         0                     0                       1
SHIPW                         0                     0                       1
GYA                           0                     0                       1
GTEG                          0                     0                       1
TCZ.CA                        0                     0                       1
SGRID                         0                     0                       1
AMC.CA                        0                     0                       1
GOZ.CA                        0                     0                       1
MILMD                         0                     0                       1
AZD.CA                        0                     0                       1
GMMB                          0                     0                       1
GLV.B.CA                      0                     0                       1
MJT                           0                     0                       1
MJY                           0                     1                       1
MKH                           0                     0                       1
MKLOG                         0                     0                       1
TGS.CA                        0                     0                       1
GIGOM                         0                     0                       1
SEZM                          0                     0                       1
GJK                           0                     0                       1

In [21]:
# the percentage of bull messages 
bullPerc = messagesTable['BULL_SCORED_MESSAGES']/messagesTable['TOTAL_SCANNED_MESSAGES']
# the percentage of bear messages
bearPerc = messagesTable['BEAR_SCORED_MESSAGES']/messagesTable['TOTAL_SCANNED_MESSAGES']

In [22]:
# neutral = total - bull - bear
neutralCounts = messagesTable['TOTAL_SCANNED_MESSAGES']-messagesTable['BULL_SCORED_MESSAGES']-messagesTable['BEAR_SCORED_MESSAGES']
# print (neutralCounts)
neutralPerc = neutralCounts/messagesTable['TOTAL_SCANNED_MESSAGES']

In [23]:
# check the total percentage = 1 or not
totalPerc = bullPerc + bearPerc + neutralPerc
# totalPerc

In [24]:
# add new columns to the table. by using 'insert(idx, col_name, value)'
messagesTable.insert(2, 'NEUTRAL_SCORED_MESSAGES', neutralCounts)
# messagesTable

In [25]:
# change data format to %
bullPerc = bullPerc.apply(lambda x: format(x, '.2%'))
bearPerc = bearPerc.apply(lambda x: format(x, '.2%'))
neutralPerc = neutralPerc.apply(lambda x: format(x, '.2%'))

In [26]:
# sentiment summary by stock exchange
sentiOutcome = messagesTable
sentiOutcome.insert(1,'BULL_PERC', bullPerc)
sentiOutcome.insert(3,'BEAR_PERC', bearPerc)
sentiOutcome.insert(5,'NEUTRAL_PERC', neutralPerc)
# sentiOutcome

In [27]:
# export to a csv file
sentiOutcome.to_csv('../data/output/sentimentSummaryByCompany.csv', encoding='utf-8')