In [1]:
import pandas as pd
import numpy as np 
import pylab as P 
# Import the module for plotting
import matplotlib.pyplot as plt
from pandas import Series,DataFrame,merge
plt.style.use('ggplot')

# Import daily data

In [2]:
# data import
dailyData = pd.read_csv('../data/csv/stocktwits_twitter_withretweets_daily.csv')
dailyData.head()

,SOURCE,SYMBOL,TIMESTAMP_UTC,BULLISH_INTENSITY,BEARISH_INTENSITY,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,BEAR_SCORED_MESSAGES,BULL_BEAR_MSG_RATIO,TOTAL_SCANNED_MESSAGES
0,stocktwits+twitter_withretweets,10GEN,2011-04-08T04:00:00Z,0,0,0,0,0,0,2
1,stocktwits+twitter_withretweets,10GEN,2011-04-16T04:00:00Z,0,0,0,0,0,0,3
2,stocktwits+twitter_withretweets,10GEN,2011-04-17T04:00:00Z,0,0,0,0,0,0,2
3,stocktwits+twitter_withretweets,10GEN,2011-04-20T04:00:00Z,0,0,0,0,0,0,1
4,stocktwits+twitter_withretweets,10GEN,2011-07-19T04:00:00Z,0,0,0,0,0,0,3

In [3]:
dailyData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7120506 entries, 0 to 7120505
Data columns (total 10 columns):
SOURCE                    object
SYMBOL                    object
TIMESTAMP_UTC             object
BULLISH_INTENSITY         float64
BEARISH_INTENSITY         float64
BULL_MINUS_BEAR           float64
BULL_SCORED_MESSAGES      int64
BEAR_SCORED_MESSAGES      int64
BULL_BEAR_MSG_RATIO       float64
TOTAL_SCANNED_MESSAGES    int64
dtypes: float64(4), int64(3), object(3)
memory usage: 597.6+ MB

# Import stocks

In [32]:
stocks = pd.read_csv('../data/csv/symbols/stocks.csv')
stocks.head()

  EXCHANGE  SYMBOL            TITLE Unnamed: 3 Unnamed: 4 Unnamed: 5
0      CME    6A_F  AUD/USD Futures        NaN        NaN        NaN
1      CME    6B_F  GBP/USD Futures        NaN        NaN        NaN
2      CME    6C_F  CAD/USD Futures        NaN        NaN        NaN
3      CME    6E_F  EUR/USD Futures        NaN        NaN        NaN
4      CME    6J_F  JPY/USD Futures        NaN        NaN        NaN

In [33]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9060 entries, 0 to 9059
Data columns (total 6 columns):
EXCHANGE      9060 non-null object
 SYMBOL       9060 non-null object
 TITLE        9060 non-null object
Unnamed: 3    1521 non-null object
Unnamed: 4    5 non-null object
Unnamed: 5    1 non-null object
dtypes: object(6)
memory usage: 495.5+ KB

In [37]:
stocks.EXCHANGE.unique()

array(['CME', 'EUREX', 'FX', 'ICE', 'INDEX', 'MISC', 'NASDAQ', 'NYSE',
       'NYSEArca', 'NYSEMkt', 'OTC', 'OTCBB', 'PRIVATE', 'TSX', 'TSXV'], dtype=object)

# Import symbols

In [4]:
# symbols import
symbols = pd.read_csv('../data/csv/symbology.csv')
symbols.head()

,exchange,symbol,sector,industry,title,all_scanned_January_2016_avg_daily,all_scored_January_2016_avg_daily,stocktwits_scanned_January_2016_avg_daily,stocktwits_scored_January_2016_avg_daily,twitter_scanned_January_2016_avg_daily,...,stocktwits_scanned_2012_avg_monthly,stocktwits_scored_2012_avg_monthly,twitter_scanned_2012_avg_monthly,twitter_scored_2012_avg_monthly,all_scanned_2011_avg_monthly,all_scored_2011_avg_monthly,stocktwits_scanned_2011_avg_monthly,stocktwits_scored_2011_avg_monthly,twitter_scanned_2011_avg_monthly,twitter_scored_2011_avg_monthly
0,NaN,CGC.CA,NaN,NaN,Canopy Growth Corp,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,1KM,NaN,NaN,1000 Markets,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,1RIOT,NaN,NaN,OneRiot,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,500HAT,NaN,NaN,500 Hats,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,56COM,NaN,NaN,56.com,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
symbols.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11444 entries, 0 to 11443
Data columns (total 47 columns):
exchange                                     10595 non-null object
symbol                                       11444 non-null object
sector                                       7192 non-null object
industry                                     7184 non-null object
title                                        11444 non-null object
all_scanned_January_2016_avg_daily           11444 non-null int64
all_scored_January_2016_avg_daily            11444 non-null int64
stocktwits_scanned_January_2016_avg_daily    11444 non-null int64
stocktwits_scored_January_2016_avg_daily     11444 non-null int64
twitter_scanned_January_2016_avg_daily       11444 non-null int64
twitter_scored_January_2016_avg_daily        11444 non-null int64
all_scanned_YTD_avg_monthly                  11444 non-null int64
all_scored_YTD_avg_monthly                   11444 non-null int64
stocktwits_scanned_YTD_avg_monthly           11444 non-null int64
stocktwits_scored_YTD_avg_monthly            11444 non-null int64
twitter_scanned_YTD_avg_monthly              11444 non-null int64
twitter_scored_YTD_avg_monthly               11444 non-null int64
all_scanned_2015_avg_monthly                 11444 non-null int64
all_scored_2015_avg_monthly                  11444 non-null int64
stocktwits_scanned_2015_avg_monthly          11444 non-null int64
stocktwits_scored_2015_avg_monthly           11444 non-null int64
twitter_scanned_2015_avg_monthly             11444 non-null int64
twitter_scored_2015_avg_monthly              11444 non-null int64
all_scanned_2014_avg_monthly                 11444 non-null int64
all_scored_2014_avg_monthly                  11444 non-null int64
stocktwits_scanned_2014_avg_monthly          11444 non-null int64
stocktwits_scored_2014_avg_monthly           11444 non-null int64
twitter_scanned_2014_avg_monthly             11444 non-null int64
twitter_scored_2014_avg_monthly              11444 non-null int64
all_scanned_2013_avg_monthly                 11444 non-null int64
all_scored_2013_avg_monthly                  11444 non-null int64
stocktwits_scanned_2013_avg_monthly          11444 non-null int64
stocktwits_scored_2013_avg_monthly           11444 non-null int64
twitter_scanned_2013_avg_monthly             11444 non-null int64
twitter_scored_2013_avg_monthly              11444 non-null int64
all_scanned_2012_avg_monthly                 11444 non-null int64
all_scored_2012_avg_monthly                  11444 non-null int64
stocktwits_scanned_2012_avg_monthly          11444 non-null int64
stocktwits_scored_2012_avg_monthly           11444 non-null int64
twitter_scanned_2012_avg_monthly             11444 non-null int64
twitter_scored_2012_avg_monthly              11444 non-null int64
all_scanned_2011_avg_monthly                 11444 non-null int64
all_scored_2011_avg_monthly                  11444 non-null int64
stocktwits_scanned_2011_avg_monthly          11444 non-null int64
stocktwits_scored_2011_avg_monthly           11444 non-null int64
twitter_scanned_2011_avg_monthly             11444 non-null int64
twitter_scored_2011_avg_monthly              11444 non-null int64
dtypes: int64(42), object(5)
memory usage: 4.2+ MB

In [5]:
exchangeArray = symbols.exchange.unique()
exchangeArray

array([nan, 'CME', 'EUREX', 'FX', 'ICE', 'INDEX', 'MISC', 'NASDAQ', 'NYSE',
       'NYSEArca', 'NYSEMkt', 'OTC', 'OTCBB', 'PRIVATE', 'TSX', 'TSXV'], dtype=object)

In [54]:
sectorArray = ['INDUSTRIAL_GOODS', 'HEALTHCARE', 'FINANCIAL', 'SERVICES',
       'UTILITIES', 'TECHNOLOGY', 'BASIC_MATERIALS', 'CONSUMER_GOODS',
       'CONGLOMERATES']
sectorArray

['INDUSTRIAL_GOODS',
 'HEALTHCARE',
 'FINANCIAL',
 'SERVICES',
 'UTILITIES',
 'TECHNOLOGY',
 'BASIC_MATERIALS',
 'CONSUMER_GOODS',
 'CONGLOMERATES']

In [64]:
indexArray = symbols[symbols['exchange'].isin(['', 'EUREX','INDEX'])].symbol.unique()
indexArray

array(['FDAX_F', 'FESX_F', 'AUDCAD', 'AUDCHF', 'AUDJPY', 'AUDNZD',
       'AUDUSD', 'BTCUSD', 'CADCHF', 'CADJPY', 'CHFJPY', 'EURAUD',
       'EURCAD', 'EURCHF', 'EURCZK', 'EURGBP', 'EURJPY', 'EURMXN',
       'EURNZD', 'EURRUB', 'EURTRY', 'EURUSD', 'EURZAR', 'GBPAUD',
       'GBPCAD', 'GBPCHF', 'GBPHKD', 'GBPJPY', 'GBPNZD', 'GBPUSD',
       'GBPZAR', 'INRUSD', 'NOKSEK', 'NZDCAD', 'NZDCHF', 'NZDJPY',
       'NZDUSD', 'USDBRL', 'USDCAD', 'USDCHF', 'USDCNY', 'USDCZK',
       'USDHUF', 'USDINR', 'USDIRR', 'USDJPY', 'USDKRW', 'USDMXN',
       'USDNGN', 'USDNOK', 'USDPLN', 'USDRUB', 'USDSEK', 'USDSGD',
       'USDTRY', 'USDZAR', 'XAGUSD', 'XAUUSD', 'XOIL', 'ADXY', 'AUS',
       'BDI', 'BEL20', 'BKX', 'BTK', 'CAC40', 'COMPQ', 'CPC', 'CRB', 'DAX',
       'DFX', 'DJIA', 'DJT', 'DJU', 'DXY', 'FTSE', 'HGX', 'HSCEI', 'HXR',
       'IBEX35', 'IPOS', 'IPXO', 'LCINDX', 'MIB40', 'MICEX', 'MSH', 'NBI',
       'NDX', 'NKY', 'NYA', 'NYMO', 'OEX', 'OMXS30', 'RUT', 'RUTX', 'RVX',
       'SENSEX', 'SOX', 'SPX', 'SPXEW', 'SSEC', 'STOXX', 'TICK', 'TRIN',
       'TYX', 'USDOLLAR', 'USDX', 'VFINX', 'VIX', 'VVIX', 'VXN', 'VXST',
       'VXV', 'VX_F', 'WIG30', 'XII'], dtype=object)

In [8]:
symbols.dtypes

exchange                                     object
symbol                                       object
sector                                       object
industry                                     object
title                                        object
all_scanned_January_2016_avg_daily            int64
all_scored_January_2016_avg_daily             int64
stocktwits_scanned_January_2016_avg_daily     int64
stocktwits_scored_January_2016_avg_daily      int64
twitter_scanned_January_2016_avg_daily        int64
twitter_scored_January_2016_avg_daily         int64
all_scanned_YTD_avg_monthly                   int64
all_scored_YTD_avg_monthly                    int64
stocktwits_scanned_YTD_avg_monthly            int64
stocktwits_scored_YTD_avg_monthly             int64
twitter_scanned_YTD_avg_monthly               int64
twitter_scored_YTD_avg_monthly                int64
all_scanned_2015_avg_monthly                  int64
all_scored_2015_avg_monthly                   int64
stocktwits_scanned_2015_avg_monthly           int64
stocktwits_scored_2015_avg_monthly            int64
twitter_scanned_2015_avg_monthly              int64
twitter_scored_2015_avg_monthly               int64
all_scanned_2014_avg_monthly                  int64
all_scored_2014_avg_monthly                   int64
stocktwits_scanned_2014_avg_monthly           int64
stocktwits_scored_2014_avg_monthly            int64
twitter_scanned_2014_avg_monthly              int64
twitter_scored_2014_avg_monthly               int64
all_scanned_2013_avg_monthly                  int64
all_scored_2013_avg_monthly                   int64
stocktwits_scanned_2013_avg_monthly           int64
stocktwits_scored_2013_avg_monthly            int64
twitter_scanned_2013_avg_monthly              int64
twitter_scored_2013_avg_monthly               int64
all_scanned_2012_avg_monthly                  int64
all_scored_2012_avg_monthly                   int64
stocktwits_scanned_2012_avg_monthly           int64
stocktwits_scored_2012_avg_monthly            int64
twitter_scanned_2012_avg_monthly              int64
twitter_scored_2012_avg_monthly               int64
all_scanned_2011_avg_monthly                  int64
all_scored_2011_avg_monthly                   int64
stocktwits_scanned_2011_avg_monthly           int64
stocktwits_scored_2011_avg_monthly            int64
twitter_scanned_2011_avg_monthly              int64
twitter_scored_2011_avg_monthly               int64
dtype: object

In [9]:
symbols.describe()

,all_scanned_January_2016_avg_daily,all_scored_January_2016_avg_daily,stocktwits_scanned_January_2016_avg_daily,stocktwits_scored_January_2016_avg_daily,twitter_scanned_January_2016_avg_daily,twitter_scored_January_2016_avg_daily,all_scanned_YTD_avg_monthly,all_scored_YTD_avg_monthly,stocktwits_scanned_YTD_avg_monthly,stocktwits_scored_YTD_avg_monthly,...,stocktwits_scanned_2012_avg_monthly,stocktwits_scored_2012_avg_monthly,twitter_scanned_2012_avg_monthly,twitter_scored_2012_avg_monthly,all_scanned_2011_avg_monthly,all_scored_2011_avg_monthly,stocktwits_scanned_2011_avg_monthly,stocktwits_scored_2011_avg_monthly,twitter_scanned_2011_avg_monthly,twitter_scored_2011_avg_monthly
count,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444,11444,11444,11444,...,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000
mean,10.797711,2.623733,2.596295,0.857917,7.971077,1.628364,0,0,0,0,...,18.762670,7.893219,68.164191,17.313352,52.076809,15.801468,9.329605,3.837207,42.524467,11.800856
std,77.531277,22.923606,30.250212,11.305452,55.201571,14.682406,0,0,0,0,...,344.342513,148.597889,626.635983,205.135724,462.841925,172.014389,126.386320,52.584767,348.485672,125.595997
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,15.000000,1.000000,2.000000,0.000000,0.000000,0.000000,2.000000,0.000000
75%,5.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0,0,0,0,...,3.000000,1.000000,35.000000,6.000000,21.000000,4.000000,2.000000,0.000000,18.000000,3.000000
max,4281.000000,1256.000000,1691.000000,590.000000,2891.000000,884.000000,0,0,0,0,...,31590.000000,13871.000000,48410.000000,14679.000000,27017.000000,9502.000000,7804.000000,3074.000000,20532.000000,8269.000000

In [10]:
# PLOT A SAMPLE: TOTAL SCANNED MESSAGES BETWEEN 1 TO 11
# dailyData['TOTAL_SCANNED_MESSAGES'].hist(range=(1,10))
# P.show()

# the histogram of the data
plt.hist(dailyData['TOTAL_SCANNED_MESSAGES'], range=[1, 10])
plt.xlabel('Number of Daily Messages')
plt.ylabel('Total Counts')
plt.grid(True)
plt.show()

In [11]:
# plt.show(dailyData.plot(kind = 'box'))

In [12]:
# merge dataset left join
dailySymbol = merge(dailyData,symbols,left_on='SYMBOL',right_on='symbol',how = "left")

In [13]:
dailySymbol = dailySymbol.ix[:,1:11]
dailySymbol.columns

Index([u'SYMBOL', u'TIMESTAMP_UTC', u'BULLISH_INTENSITY', u'BEARISH_INTENSITY',
       u'BULL_MINUS_BEAR', u'BULL_SCORED_MESSAGES', u'BEAR_SCORED_MESSAGES',
       u'BULL_BEAR_MSG_RATIO', u'TOTAL_SCANNED_MESSAGES', u'exchange'],
      dtype='object')

In [14]:
dailySymbol.head()

,SYMBOL,TIMESTAMP_UTC,BULLISH_INTENSITY,BEARISH_INTENSITY,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,BEAR_SCORED_MESSAGES,BULL_BEAR_MSG_RATIO,TOTAL_SCANNED_MESSAGES,exchange
0,10GEN,2011-04-08T04:00:00Z,0,0,0,0,0,0,2,PRIVATE
1,10GEN,2011-04-16T04:00:00Z,0,0,0,0,0,0,3,PRIVATE
2,10GEN,2011-04-17T04:00:00Z,0,0,0,0,0,0,2,PRIVATE
3,10GEN,2011-04-20T04:00:00Z,0,0,0,0,0,0,1,PRIVATE
4,10GEN,2011-07-19T04:00:00Z,0,0,0,0,0,0,3,PRIVATE

In [15]:
# Group By Stock Exchange
companyGrouped = dailySymbol.groupby(dailySymbol['SYMBOL'])
sumByCompany = companyGrouped.sum()
print(sumByCompany.columns)
# sumByExchange

Index([u'BULLISH_INTENSITY', u'BEARISH_INTENSITY', u'BULL_MINUS_BEAR',
       u'BULL_SCORED_MESSAGES', u'BEAR_SCORED_MESSAGES',
       u'BULL_BEAR_MSG_RATIO', u'TOTAL_SCANNED_MESSAGES'],
      dtype='object')

In [16]:
companyGrouped.head()

,BEARISH_INTENSITY,BEAR_SCORED_MESSAGES,BULLISH_INTENSITY,BULL_BEAR_MSG_RATIO,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,TIMESTAMP_UTC,TOTAL_SCANNED_MESSAGES,exchange
0,0.00,0,0.00,0,0.00,0,2011-04-08T04:00:00Z,2,PRIVATE
1,0.00,0,0.00,0,0.00,0,2011-04-16T04:00:00Z,3,PRIVATE
2,0.00,0,0.00,0,0.00,0,2011-04-17T04:00:00Z,2,PRIVATE
3,0.00,0,0.00,0,0.00,0,2011-04-20T04:00:00Z,1,PRIVATE
4,0.00,0,0.00,0,0.00,0,2011-07-19T04:00:00Z,3,PRIVATE
86,0.00,0,1.91,0,1.91,1,2015-11-23T05:00:00Z,1,NaN
87,0.00,0,0.00,0,0.00,0,2010-01-21T05:00:00Z,4,PRIVATE
88,0.00,0,0.89,0,0.89,1,2010-01-29T05:00:00Z,1,PRIVATE
89,0.00,0,0.00,0,0.00,0,2010-02-25T05:00:00Z,1,PRIVATE
90,0.00,0,0.00,0,0.00,0,2010-03-09T05:00:00Z,1,PRIVATE
91,2.00,1,0.00,0,-2.00,0,2010-04-06T04:00:00Z,1,PRIVATE
211,0.00,0,0.00,0,0.00,0,2009-07-28T04:00:00Z,1,CME
212,0.00,0,0.00,0,0.00,0,2009-12-03T05:00:00Z,1,CME
213,0.00,0,2.11,0,2.11,1,2010-03-28T04:00:00Z,1,CME
214,2.06,1,0.00,0,-2.06,0,2010-03-29T04:00:00Z,1,CME
215,0.00,0,1.26,0,1.26,1,2010-04-23T04:00:00Z,1,CME
1458,0.00,0,0.00,0,0.00,0,2009-10-02T04:00:00Z,1,CME
1459,1.17,1,0.00,0,-1.17,0,2010-01-06T05:00:00Z,1,CME
1460,0.00,0,1.11,0,1.11,1,2010-02-18T05:00:00Z,1,CME
1461,0.00,0,0.00,0,0.00,0,2010-02-25T05:00:00Z,1,CME
1462,1.90,1,0.00,0,-1.90,0,2010-03-25T04:00:00Z,3,CME
2325,0.00,0,0.00,0,0.00,0,2009-12-03T05:00:00Z,2,CME
2326,0.00,0,2.11,0,2.11,1,2010-03-28T04:00:00Z,1,CME
2327,2.06,1,0.00,0,-2.06,0,2010-03-29T04:00:00Z,1,CME
2328,0.17,1,0.00,0,-0.17,0,2010-04-13T04:00:00Z,1,CME
2329,1.02,2,0.00,0,-1.02,0,2010-04-14T04:00:00Z,2,CME
3090,2.67,1,0.00,0,-2.67,0,2009-09-01T04:00:00Z,1,CME
3091,1.50,1,0.00,0,-1.50,0,2009-09-02T04:00:00Z,1,CME
3092,0.00,0,0.00,0,0.00,0,2009-09-03T04:00:00Z,1,CME
3093,0.00,0,0.00,0,0.00,0,2009-09-10T04:00:00Z,1,CME
...,...,...,...,...,...,...,...,...,...
7118447,0.00,0,0.00,0,0.00,0,2009-11-20T05:00:00Z,1,NASDAQ
7118448,0.55,1,1.92,1,1.37,1,2010-01-28T05:00:00Z,2,NASDAQ
7118449,0.00,0,0.00,0,0.00,0,2010-03-04T05:00:00Z,1,NASDAQ
7118450,2.80,1,0.00,0,-2.80,0,2010-03-11T05:00:00Z,1,NASDAQ
7119754,0.00,0,0.00,0,0.00,0,2010-03-14T05:00:00Z,1,CME
7119755,0.05,1,0.00,0,-0.05,0,2010-03-21T04:00:00Z,1,CME
7119756,0.00,0,0.00,0,0.00,0,2010-04-09T04:00:00Z,1,CME
7119757,0.00,0,0.90,0,0.90,1,2010-05-06T04:00:00Z,1,CME
7119758,0.00,0,0.00,0,0.00,0,2010-06-04T04:00:00Z,1,CME
7121487,0.00,0,0.00,0,0.00,0,2010-12-27T05:00:00Z,1,NYSE
7121488,0.00,0,0.00,0,0.00,0,2011-04-19T04:00:00Z,1,NYSE
7121489,0.00,0,0.00,0,0.00,0,2011-04-28T04:00:00Z,2,NYSE
7121490,0.00,0,0.00,0,0.00,0,2011-05-02T04:00:00Z,1,NYSE
7121491,0.00,0,0.00,0,0.00,0,2011-05-03T04:00:00Z,1,NYSE
7122180,0.00,0,0.00,0,0.00,0,2015-07-12T04:00:00Z,1,NASDAQ
7122181,0.00,0,0.00,0,0.00,0,2015-07-23T04:00:00Z,8,NASDAQ
7122182,0.00,0,0.00,0,0.00,0,2015-07-24T04:00:00Z,3,NASDAQ
7122183,0.00,0,0.00,0,0.00,0,2015-07-26T04:00:00Z,1,NASDAQ
7122184,0.00,0,0.00,0,0.00,0,2015-07-27T04:00:00Z,4,NASDAQ
7122346,0.00,0,0.00,0,0.00,0,2009-12-10T05:00:00Z,1,NYSE
7122347,0.27,1,0.00,0,-0.27,0,2009-12-11T05:00:00Z,1,NYSE
7122348,0.00,0,1.94,0,1.94,1,2010-01-08T05:00:00Z,1,NYSE
7122349,2.15,1,0.00,0,-2.15,0,2010-03-30T04:00:00Z,4,NYSE
7122350,0.00,0,0.00,0,0.00,0,2010-03-31T04:00:00Z,1,NYSE
7123012,0.00,0,0.00,0,0.00,0,2014-09-12T04:00:00Z,1,PRIVATE
7123013,0.00,0,0.00,0,0.00,0,2015-08-05T04:00:00Z,2,TSX
7123014,0.00,0,0.00,0,0.00,0,2015-08-06T04:00:00Z,1,TSX
7123015,0.00,0,0.00,0,0.00,0,2015-08-07T04:00:00Z,4,TSX
7123016,0.00,0,0.00,0,0.00,0,2015-08-10T04:00:00Z,2,TSX
7123017,0.00,0,0.00,0,0.00,0,2015-10-15T04:00:00Z,1,TSX

In [17]:
# statistic description for bull bear messages ratio by exchanges
statByCompany_Ratio = companyGrouped['BULL_BEAR_MSG_RATIO'].describe()
statByCompany = companyGrouped.describe()
# export the statistic description by exchanges
statByCompany.to_csv('../data/output/statByCompany.csv', encoding='utf-8')

In [61]:
# a table only contains the total quality of bullish, bearish and total messages for each exchange
messagesTable = sumByCompany.ix[:,[3,4,6]]
messagesTableSorted = messagesTable.sort('TOTAL_SCANNED_MESSAGES', ascending=False)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()

In [19]:
messagesTableSorted.index.values

array(['MARKET', 'SP500', 'TECHNOLOGY', ..., 'GIGOM', 'SEZM', 'GJK'], dtype=object)

In [34]:
# transform sector array to uppercase
sectorArray

AttributeError: 'numpy.ndarray' object has no attribute 'remove'

In [60]:
# filter data to remove sectors
sectorArray
# filterArray = np.concatenate([exchangeArray,sectorArray, indexArray])
filterArray = np.concatenate([exchangeArray, sectorArray, ['MARKET']])
# [x.upper() for x in filterArray]
filterArray

array([nan, 'CME', 'EUREX', 'FX', 'ICE', 'INDEX', 'MISC', 'NASDAQ', 'NYSE',
       'NYSEArca', 'NYSEMkt', 'OTC', 'OTCBB', 'PRIVATE', 'TSX', 'TSXV',
       'INDUSTRIAL_GOODS', 'HEALTHCARE', 'FINANCIAL', 'SERVICES',
       'UTILITIES', 'TECHNOLOGY', 'BASIC_MATERIALS', 'CONSUMER_GOODS',
       'CONGLOMERATES', 'MARKET'], dtype=object)

In [62]:
messagesTableSorted = messagesTableSorted[~messagesTableSorted.index.isin(filterArray)]

In [63]:
messagesTableSorted.head(25)

        BULL_SCORED_MESSAGES  BEAR_SCORED_MESSAGES  TOTAL_SCANNED_MESSAGES
SYMBOL
SP500                9129743               4190486                54079643
AAPL                  880890                519740                 4616061
SPY                   654165                465827                 3146593
AP                     40010                 16977                 2115709
FB                    315576                154990                 1641991
EURUSD                341587                350623                 1554327
SPX                   269023                189098                 1225937
ES_F                  225130                207174                 1139647
GOOG                  173229                 74705                 1070324
TWTR                  179713                 91494                  995293
TSLA                  175345                112664                  917347
NFLX                  165530                112302                  843009
AMZN                  159706                 73264                  826710
PS_OIL                119102                 99863                  671177
QQQ                   126655                 90058                  654196
GLD                   120295                 75043                  639233
MSFT                   74028                 30112                  567506
BBRY                  106400                 60940                  559131
GBPUSD                139244                138193                  554523
USDJPY                121985                 88484                  536896
IWM                    93735                 66223                  498560
BAC                    79934                 36842                  444279
BABA                   80080                 41682                  426519
PLUG                   90920                 45966                  407219
CL_F                   81813                 75517                  394751

In [ ]:
messagesTableSorted.tail(25)

In [ ]:
# the percentage of bull messages 
bullPerc = messagesTable['BULL_SCORED_MESSAGES']/messagesTable['TOTAL_SCANNED_MESSAGES']
# the percentage of bear messages
bearPerc = messagesTable['BEAR_SCORED_MESSAGES']/messagesTable['TOTAL_SCANNED_MESSAGES']

In [ ]:
# neutral = total - bull - bear
neutralCounts = messagesTable['TOTAL_SCANNED_MESSAGES']-messagesTable['BULL_SCORED_MESSAGES']-messagesTable['BEAR_SCORED_MESSAGES']
# print (neutralCounts)
neutralPerc = neutralCounts/messagesTable['TOTAL_SCANNED_MESSAGES']

In [ ]:
# check the total percentage = 1 or not
totalPerc = bullPerc + bearPerc + neutralPerc
# totalPerc

In [ ]:
# add new columns to the table. by using 'insert(idx, col_name, value)'
messagesTable.insert(2, 'NEUTRAL_SCORED_MESSAGES', neutralCounts)
# messagesTable

In [ ]:
# change data format to %
bullPerc = bullPerc.apply(lambda x: format(x, '.2%'))
bearPerc = bearPerc.apply(lambda x: format(x, '.2%'))
neutralPerc = neutralPerc.apply(lambda x: format(x, '.2%'))

In [ ]:
# sentiment summary by stock exchange
sentiOutcome = messagesTable
sentiOutcome.insert(1,'BULL_PERC', bullPerc)
sentiOutcome.insert(3,'BEAR_PERC', bearPerc)
sentiOutcome.insert(5,'NEUTRAL_PERC', neutralPerc)
# sentiOutcome

In [ ]:
# export to a csv file
sentiOutcome.to_csv('../data/output/sentimentSummaryByCompany.csv', encoding='utf-8')