In [91]:
import pandas as pd
import numpy as np 
import pylab as P 
from datetime import datetime
# Import the module for plotting
import matplotlib.pyplot as plt
from pandas import Series,DataFrame,merge
plt.style.use('ggplot')

# Import daily data

In [2]:
# data import
dailyData = pd.read_csv('../data/csv/stocktwits_twitter_withretweets_daily.csv')
dailyData.head()

,SOURCE,SYMBOL,TIMESTAMP_UTC,BULLISH_INTENSITY,BEARISH_INTENSITY,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,BEAR_SCORED_MESSAGES,BULL_BEAR_MSG_RATIO,TOTAL_SCANNED_MESSAGES
0,stocktwits+twitter_withretweets,10GEN,2011-04-08T04:00:00Z,0,0,0,0,0,0,2
1,stocktwits+twitter_withretweets,10GEN,2011-04-16T04:00:00Z,0,0,0,0,0,0,3
2,stocktwits+twitter_withretweets,10GEN,2011-04-17T04:00:00Z,0,0,0,0,0,0,2
3,stocktwits+twitter_withretweets,10GEN,2011-04-20T04:00:00Z,0,0,0,0,0,0,1
4,stocktwits+twitter_withretweets,10GEN,2011-07-19T04:00:00Z,0,0,0,0,0,0,3

In [3]:
dailyData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7120506 entries, 0 to 7120505
Data columns (total 10 columns):
SOURCE                    object
SYMBOL                    object
TIMESTAMP_UTC             object
BULLISH_INTENSITY         float64
BEARISH_INTENSITY         float64
BULL_MINUS_BEAR           float64
BULL_SCORED_MESSAGES      int64
BEAR_SCORED_MESSAGES      int64
BULL_BEAR_MSG_RATIO       float64
TOTAL_SCANNED_MESSAGES    int64
dtypes: float64(4), int64(3), object(3)
memory usage: 597.6+ MB

### Determine date range

In [97]:
# dailyData['TIMESTAMP_UTC'].max()
# 2016-01-07T05:00:00Z
# dt.strptime()
utcmax = datetime.strptime(dailyData['TIMESTAMP_UTC'].max(), '%Y-%m-%dT%H:%M:%SZ')
utcmin = datetime.strptime(dailyData['TIMESTAMP_UTC'].min(), '%Y-%m-%dT%H:%M:%SZ')
epoch = (utcmax - utcmin).days
epoch
# dt.strptime()

2372

# Import stocks

In [4]:
stocks = pd.read_csv('../data/csv/symbols/stocks.csv')
stocks.head()

  EXCHANGE SYMBOL            TITLE Unnamed: 3 Unnamed: 4 Unnamed: 5
0      CME   6A_F  AUD/USD Futures        NaN        NaN        NaN
1      CME   6B_F  GBP/USD Futures        NaN        NaN        NaN
2      CME   6C_F  CAD/USD Futures        NaN        NaN        NaN
3      CME   6E_F  EUR/USD Futures        NaN        NaN        NaN
4      CME   6J_F  JPY/USD Futures        NaN        NaN        NaN

In [5]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9060 entries, 0 to 9059
Data columns (total 6 columns):
EXCHANGE      9060 non-null object
SYMBOL        9060 non-null object
TITLE         9060 non-null object
Unnamed: 3    1521 non-null object
Unnamed: 4    5 non-null object
Unnamed: 5    1 non-null object
dtypes: object(6)
memory usage: 495.5+ KB

In [6]:
stocks.describe()

,EXCHANGE,SYMBOL,TITLE,Unnamed: 3,Unnamed: 4,Unnamed: 5
count,9060,9060,9060,1521,5,1
unique,15,9057,8909,50,4,1
top,NASDAQ,PNP.CA,Merrill Lynch Depositor\,Inc.,Inc.,Oyo Oilfield
freq,3071,2,11,1331,2,1

In [7]:
# merge dataset left join
dailyStocks = merge(dailyData, stocks, left_on='SYMBOL', right_on='SYMBOL', how = "left")

In [8]:
dailyStocks = dailyStocks.ix[:,1:11]
dailyStocks.head()

,SYMBOL,TIMESTAMP_UTC,BULLISH_INTENSITY,BEARISH_INTENSITY,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,BEAR_SCORED_MESSAGES,BULL_BEAR_MSG_RATIO,TOTAL_SCANNED_MESSAGES,EXCHANGE
0,10GEN,2011-04-08T04:00:00Z,0,0,0,0,0,0,2,PRIVATE
1,10GEN,2011-04-16T04:00:00Z,0,0,0,0,0,0,3,PRIVATE
2,10GEN,2011-04-17T04:00:00Z,0,0,0,0,0,0,2,PRIVATE
3,10GEN,2011-04-20T04:00:00Z,0,0,0,0,0,0,1,PRIVATE
4,10GEN,2011-07-19T04:00:00Z,0,0,0,0,0,0,3,PRIVATE

In [56]:
# Group By Stock Exchange
companyGrouped = dailyStocks.groupby(['SYMBOL'])
sumByCompany = companyGrouped.sum()
# sumByExchange

In [55]:
companyGrouped.head()

,BEARISH_INTENSITY,BEAR_SCORED_MESSAGES,BULLISH_INTENSITY,BULL_BEAR_MSG_RATIO,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,EXCHANGE,TIMESTAMP_UTC,TOTAL_SCANNED_MESSAGES
0,0.00,0,0.00,0,0.00,0,PRIVATE,2011-04-08T04:00:00Z,2
1,0.00,0,0.00,0,0.00,0,PRIVATE,2011-04-16T04:00:00Z,3
2,0.00,0,0.00,0,0.00,0,PRIVATE,2011-04-17T04:00:00Z,2
3,0.00,0,0.00,0,0.00,0,PRIVATE,2011-04-20T04:00:00Z,1
4,0.00,0,0.00,0,0.00,0,PRIVATE,2011-07-19T04:00:00Z,3
86,0.00,0,1.91,0,1.91,1,NaN,2015-11-23T05:00:00Z,1
87,0.00,0,0.00,0,0.00,0,PRIVATE,2010-01-21T05:00:00Z,4
88,0.00,0,0.89,0,0.89,1,PRIVATE,2010-01-29T05:00:00Z,1
89,0.00,0,0.00,0,0.00,0,PRIVATE,2010-02-25T05:00:00Z,1
90,0.00,0,0.00,0,0.00,0,PRIVATE,2010-03-09T05:00:00Z,1
91,2.00,1,0.00,0,-2.00,0,PRIVATE,2010-04-06T04:00:00Z,1
211,0.00,0,0.00,0,0.00,0,CME,2009-07-28T04:00:00Z,1
212,0.00,0,0.00,0,0.00,0,CME,2009-12-03T05:00:00Z,1
213,0.00,0,2.11,0,2.11,1,CME,2010-03-28T04:00:00Z,1
214,2.06,1,0.00,0,-2.06,0,CME,2010-03-29T04:00:00Z,1
215,0.00,0,1.26,0,1.26,1,CME,2010-04-23T04:00:00Z,1
1458,0.00,0,0.00,0,0.00,0,CME,2009-10-02T04:00:00Z,1
1459,1.17,1,0.00,0,-1.17,0,CME,2010-01-06T05:00:00Z,1
1460,0.00,0,1.11,0,1.11,1,CME,2010-02-18T05:00:00Z,1
1461,0.00,0,0.00,0,0.00,0,CME,2010-02-25T05:00:00Z,1
1462,1.90,1,0.00,0,-1.90,0,CME,2010-03-25T04:00:00Z,3
2325,0.00,0,0.00,0,0.00,0,CME,2009-12-03T05:00:00Z,2
2326,0.00,0,2.11,0,2.11,1,CME,2010-03-28T04:00:00Z,1
2327,2.06,1,0.00,0,-2.06,0,CME,2010-03-29T04:00:00Z,1
2328,0.17,1,0.00,0,-0.17,0,CME,2010-04-13T04:00:00Z,1
2329,1.02,2,0.00,0,-1.02,0,CME,2010-04-14T04:00:00Z,2
3090,2.67,1,0.00,0,-2.67,0,CME,2009-09-01T04:00:00Z,1
3091,1.50,1,0.00,0,-1.50,0,CME,2009-09-02T04:00:00Z,1
3092,0.00,0,0.00,0,0.00,0,CME,2009-09-03T04:00:00Z,1
3093,0.00,0,0.00,0,0.00,0,CME,2009-09-10T04:00:00Z,1
...,...,...,...,...,...,...,...,...,...
7117623,0.00,0,0.00,0,0.00,0,NASDAQ,2009-11-20T05:00:00Z,1
7117624,0.55,1,1.92,1,1.37,1,NASDAQ,2010-01-28T05:00:00Z,2
7117625,0.00,0,0.00,0,0.00,0,NASDAQ,2010-03-04T05:00:00Z,1
7117626,2.80,1,0.00,0,-2.80,0,NASDAQ,2010-03-11T05:00:00Z,1
7118930,0.00,0,0.00,0,0.00,0,CME,2010-03-14T05:00:00Z,1
7118931,0.05,1,0.00,0,-0.05,0,CME,2010-03-21T04:00:00Z,1
7118932,0.00,0,0.00,0,0.00,0,CME,2010-04-09T04:00:00Z,1
7118933,0.00,0,0.90,0,0.90,1,CME,2010-05-06T04:00:00Z,1
7118934,0.00,0,0.00,0,0.00,0,CME,2010-06-04T04:00:00Z,1
7120663,0.00,0,0.00,0,0.00,0,NYSE,2010-12-27T05:00:00Z,1
7120664,0.00,0,0.00,0,0.00,0,NYSE,2011-04-19T04:00:00Z,1
7120665,0.00,0,0.00,0,0.00,0,NYSE,2011-04-28T04:00:00Z,2
7120666,0.00,0,0.00,0,0.00,0,NYSE,2011-05-02T04:00:00Z,1
7120667,0.00,0,0.00,0,0.00,0,NYSE,2011-05-03T04:00:00Z,1
7121356,0.00,0,0.00,0,0.00,0,NaN,2015-07-12T04:00:00Z,1
7121357,0.00,0,0.00,0,0.00,0,NaN,2015-07-23T04:00:00Z,8
7121358,0.00,0,0.00,0,0.00,0,NaN,2015-07-24T04:00:00Z,3
7121359,0.00,0,0.00,0,0.00,0,NaN,2015-07-26T04:00:00Z,1
7121360,0.00,0,0.00,0,0.00,0,NaN,2015-07-27T04:00:00Z,4
7121522,0.00,0,0.00,0,0.00,0,NYSE,2009-12-10T05:00:00Z,1
7121523,0.27,1,0.00,0,-0.27,0,NYSE,2009-12-11T05:00:00Z,1
7121524,0.00,0,1.94,0,1.94,1,NYSE,2010-01-08T05:00:00Z,1
7121525,2.15,1,0.00,0,-2.15,0,NYSE,2010-03-30T04:00:00Z,4
7121526,0.00,0,0.00,0,0.00,0,NYSE,2010-03-31T04:00:00Z,1
7122188,0.00,0,0.00,0,0.00,0,NaN,2014-09-12T04:00:00Z,1
7122189,0.00,0,0.00,0,0.00,0,NaN,2015-08-05T04:00:00Z,2
7122190,0.00,0,0.00,0,0.00,0,NaN,2015-08-06T04:00:00Z,1
7122191,0.00,0,0.00,0,0.00,0,NaN,2015-08-07T04:00:00Z,4
7122192,0.00,0,0.00,0,0.00,0,NaN,2015-08-10T04:00:00Z,2
7122193,0.00,0,0.00,0,0.00,0,NaN,2015-10-15T04:00:00Z,1

In [52]:
sumByCompany.head()

,BULLISH_INTENSITY,BEARISH_INTENSITY,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,BEAR_SCORED_MESSAGES,BULL_BEAR_MSG_RATIO,TOTAL_SCANNED_MESSAGES
SYMBOL,,,,,,,
10GEN,6.69,12.41,-5.72,5,7,0.50,435
1KM,1.91,0.00,1.91,1,0,0.00,1
4SQ,21.79,11.82,9.97,21,12,0.00,291
6A_F,989.44,754.62,234.82,1502,993,289.06,8381
6B_F,426.43,378.11,48.32,628,496,148.73,3054

# Form descriptive statistics and save output to file

In [11]:
# statistic description for bull bear messages ratio by exchanges
statByCompany_Ratio = companyGrouped['BULL_BEAR_MSG_RATIO'].describe()
statByCompany = companyGrouped.describe()
# export the statistic description by exchanges
statByCompany.to_csv('../data/output/statByCompany.csv', encoding='utf-8')

In [68]:
# a table only contains the total quality of bullish, bearish and total messages for each exchange
messagesTable = sumByCompany.ix[:,[3,4,6]]
messagesTableSorted = messagesTable.sort('TOTAL_SCANNED_MESSAGES', ascending=False)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()

# Filter top 30 companies

In [24]:
# filter data to remove sectors

sectorArray = ['INDUSTRIAL_GOODS', 'HEALTHCARE', 'FINANCIAL', 'SERVICES',
               'UTILITIES', 'TECHNOLOGY', 'BASIC_MATERIALS', 'CONSUMER_GOODS',
               'CONGLOMERATES']
indexArray = stocks.loc[~stocks['EXCHANGE'].isin(['NASDAQ', 'NYSE'])].SYMBOL.unique()
filterArray = np.concatenate([indexArray, sectorArray, ['MARKET', 'SP500']])
filterArray

array(['6A_F', '6B_F', '6C_F', ..., 'CONGLOMERATES', 'MARKET', 'SP500'], dtype=object)

In [69]:
messagesTableSorted = messagesTableSorted[~messagesTableSorted.index.isin(filterArray)]

In [124]:
top30.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, AAPL to LNKD
Data columns (total 3 columns):
BULL_SCORED_MESSAGES      30 non-null int64
BEAR_SCORED_MESSAGES      30 non-null int64
TOTAL_SCANNED_MESSAGES    30 non-null int64
dtypes: int64(3)
memory usage: 960.0+ bytes

In [123]:
top30 = messagesTableSorted.head(30)
top30 = merge(top30, stocks, left_on=top30.index, right_on='SYMBOL', how = "left")
top30

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [98]:
top30.describe()

       BULL_SCORED_MESSAGES  BEAR_SCORED_MESSAGES  TOTAL_SCANNED_MESSAGES
count             30.000000              30.00000               30.000000
mean          108539.133333           59859.40000           696861.733333
std           159828.447169           94838.26564           851364.147741
min             4826.000000            1726.00000           280473.000000
25%            40346.500000           16250.25000           323622.750000
50%            65324.500000           32988.00000           376818.500000
75%           115926.500000           70183.00000           666931.750000
max           880890.000000          519740.00000          4616061.000000

In [29]:
# the percentage of bull messages 
bullPerc = messagesTable['BULL_SCORED_MESSAGES']/messagesTable['TOTAL_SCANNED_MESSAGES']
# the percentage of bear messages
bearPerc = messagesTable['BEAR_SCORED_MESSAGES']/messagesTable['TOTAL_SCANNED_MESSAGES']

In [30]:
# neutral = total - bull - bear
neutralCounts = messagesTable['TOTAL_SCANNED_MESSAGES']-messagesTable['BULL_SCORED_MESSAGES']-messagesTable['BEAR_SCORED_MESSAGES']
# print (neutralCounts)
neutralPerc = neutralCounts/messagesTable['TOTAL_SCANNED_MESSAGES']

In [31]:
# check the total percentage = 1 or not
totalPerc = bullPerc + bearPerc + neutralPerc
# totalPerc

In [32]:
# add new columns to the table. by using 'insert(idx, col_name, value)'
messagesTable.insert(2, 'NEUTRAL_SCORED_MESSAGES', neutralCounts)
# messagesTable

In [33]:
# change data format to %
bullPerc = bullPerc.apply(lambda x: format(x, '.2%'))
bearPerc = bearPerc.apply(lambda x: format(x, '.2%'))
neutralPerc = neutralPerc.apply(lambda x: format(x, '.2%'))

In [34]:
# sentiment summary by stock exchange
sentiOutcome = messagesTable
sentiOutcome.insert(1,'BULL_PERC', bullPerc)
sentiOutcome.insert(3,'BEAR_PERC', bearPerc)
sentiOutcome.insert(5,'NEUTRAL_PERC', neutralPerc)
# sentiOutcome

In [35]:
sentiOutcome.loc[sentiOutcome.]

,BULL_SCORED_MESSAGES,BULL_PERC,BEAR_SCORED_MESSAGES,BEAR_PERC,NEUTRAL_SCORED_MESSAGES,NEUTRAL_PERC,TOTAL_SCANNED_MESSAGES
SYMBOL,,,,,,,
10GEN,5,1.15%,7,1.61%,423,97.24%,435
1KM,1,100.00%,0,0.00%,0,0.00%,1
4SQ,21,7.22%,12,4.12%,258,88.66%,291
6A_F,1502,17.92%,993,11.85%,5886,70.23%,8381
6B_F,628,20.56%,496,16.24%,1930,63.20%,3054
6C_F,581,23.10%,331,13.16%,1603,63.74%,2515
6E_F,5658,12.04%,13719,29.20%,27610,58.76%,46987
6J_F,1487,18.73%,1396,17.58%,5057,63.69%,7940
6M_F,59,26.70%,56,25.34%,106,47.96%,221
6N_F,87,19.42%,81,18.08%,280,62.50%,448
6Q_F,0,0.00%,0,0.00%,6,100.00%,6
6S_F,227,26.64%,84,9.86%,541,63.50%,852
8Q_F,15,19.23%,8,10.26%,55,70.51%,78
A,24991,11.06%,12382,5.48%,188531,83.46%,225904
AA,24842,16.56%,9133,6.09%,116054,77.35%,150029
AAA.CA,32,20.00%,6,3.75%,122,76.25%,160
AAAP,22,10.78%,3,1.47%,179,87.75%,204
AAB.CA,5,9.26%,0,0.00%,49,90.74%,54
AAC,861,17.51%,321,6.53%,3736,75.97%,4918
AACC,35,5.45%,9,1.40%,598,93.15%,642
AACOU,0,0.00%,0,0.00%,12,100.00%,12
AADR,8,3.14%,1,0.39%,246,96.47%,255
AAH.CA,6,17.65%,0,0.00%,28,82.35%,34
AAI,26,2.58%,29,2.87%,954,94.55%,1009
AAIIQ,5,9.26%,0,0.00%,49,90.74%,54
AAL,16929,18.85%,6882,7.66%,65992,73.49%,89803
AAMC,372,16.76%,299,13.47%,1548,69.76%,2219
AAME,195,5.39%,42,1.16%,3378,93.44%,3615
AAN,2025,18.17%,285,2.56%,8833,79.27%,11143
AAOI,831,17.31%,154,3.21%,3816,79.48%,4801
...,...,...,...,...,...,...,...
ZOLL,297,25.94%,46,4.02%,802,70.04%,1145
ZOLT,961,22.75%,224,5.30%,3040,71.95%,4225
ZOOG,18,14.75%,17,13.93%,87,71.31%,122
ZOOM,683,15.59%,244,5.57%,3455,78.85%,4382
ZOSK,0,0.00%,0,0.00%,4,100.00%,4
ZO_F,260,27.03%,188,19.54%,514,53.43%,962
ZPCR,6,37.50%,0,0.00%,10,62.50%,16
ZPIN,680,21.24%,125,3.91%,2396,74.85%,3201
ZQK,2858,20.24%,1296,9.18%,9964,70.58%,14118
ZQ_F,65,13.10%,47,9.48%,384,77.42%,496
ZRAN,55,11.20%,19,3.87%,417,84.93%,491
ZROZ,325,16.89%,106,5.51%,1493,77.60%,1924
ZR_F,74,32.03%,22,9.52%,135,58.44%,231
ZSAN,222,17.73%,97,7.75%,933,74.52%,1252
ZSL,2037,21.41%,1633,17.16%,5844,61.43%,9514
ZSPH,1623,19.50%,469,5.63%,6231,74.86%,8323
ZSTN,325,17.78%,148,8.10%,1355,74.12%,1828
ZS_F,9360,25.13%,3859,10.36%,24031,64.51%,37250
ZTR,157,19.70%,23,2.89%,617,77.42%,797
ZTS,2667,18.45%,709,4.91%,11078,76.64%,14454
ZT_F,210,22.29%,114,12.10%,618,65.61%,942
ZU,3994,22.92%,2341,13.43%,11094,63.65%,17429
ZUMZ,2199,18.93%,775,6.67%,8642,74.40%,11616
ZW_F,6477,21.92%,2761,9.34%,20310,68.74%,29548
ZX,89,3.44%,33,1.27%,2468,95.29%,2590
ZYNE,245,8.34%,85,2.89%,2608,88.77%,2938
ZZ,371,14.64%,126,4.97%,2037,80.39%,2534
ZZLE,0,0.00%,0,0.00%,1,100.00%,1
ZZZ.CA,0,0.00%,2,11.76%,15,88.24%,17
symbol,11,13.75%,7,8.75%,62,77.50%,80

In [ ]:
# export to a csv file
sentiOutcome.to_csv('../data/output/sentimentSummaryByCompany.csv', encoding='utf-8')