In [1]:
import pandas as pd
import numpy as np 
import pylab as P 
# Import the module for plotting
import matplotlib.pyplot as plt
from pandas import Series,DataFrame,merge
plt.style.use('ggplot')

# Import daily data

In [2]:
# data import
dailyData = pd.read_csv('../data/csv/stocktwits_twitter_withretweets_daily.csv')
dailyData.head()

,SOURCE,SYMBOL,TIMESTAMP_UTC,BULLISH_INTENSITY,BEARISH_INTENSITY,BULL_MINUS_BEAR,BULL_SCORED_MESSAGES,BEAR_SCORED_MESSAGES,BULL_BEAR_MSG_RATIO,TOTAL_SCANNED_MESSAGES
0,stocktwits+twitter_withretweets,10GEN,2011-04-08T04:00:00Z,0,0,0,0,0,0,2
1,stocktwits+twitter_withretweets,10GEN,2011-04-16T04:00:00Z,0,0,0,0,0,0,3
2,stocktwits+twitter_withretweets,10GEN,2011-04-17T04:00:00Z,0,0,0,0,0,0,2
3,stocktwits+twitter_withretweets,10GEN,2011-04-20T04:00:00Z,0,0,0,0,0,0,1
4,stocktwits+twitter_withretweets,10GEN,2011-07-19T04:00:00Z,0,0,0,0,0,0,3

In [10]:
dailyData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7120506 entries, 0 to 7120505
Data columns (total 10 columns):
SOURCE                    object
SYMBOL                    object
TIMESTAMP_UTC             object
BULLISH_INTENSITY         float64
BEARISH_INTENSITY         float64
BULL_MINUS_BEAR           float64
BULL_SCORED_MESSAGES      int64
BEAR_SCORED_MESSAGES      int64
BULL_BEAR_MSG_RATIO       float64
TOTAL_SCANNED_MESSAGES    int64
dtypes: float64(4), int64(3), object(3)
memory usage: 597.6+ MB

# Import symbols

In [4]:
# symbols import
symbols = pd.read_csv('../data/csv/symbology.csv')
symbols.head()

,exchange,symbol,sector,industry,title,all_scanned_January_2016_avg_daily,all_scored_January_2016_avg_daily,stocktwits_scanned_January_2016_avg_daily,stocktwits_scored_January_2016_avg_daily,twitter_scanned_January_2016_avg_daily,...,stocktwits_scanned_2012_avg_monthly,stocktwits_scored_2012_avg_monthly,twitter_scanned_2012_avg_monthly,twitter_scored_2012_avg_monthly,all_scanned_2011_avg_monthly,all_scored_2011_avg_monthly,stocktwits_scanned_2011_avg_monthly,stocktwits_scored_2011_avg_monthly,twitter_scanned_2011_avg_monthly,twitter_scored_2011_avg_monthly
0,NaN,CGC.CA,NaN,NaN,Canopy Growth Corp,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,1KM,NaN,NaN,1000 Markets,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NaN,1RIOT,NaN,NaN,OneRiot,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,500HAT,NaN,NaN,500 Hats,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,56COM,NaN,NaN,56.com,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
symbols.dtypes

exchange                                     object
symbol                                       object
sector                                       object
industry                                     object
title                                        object
all_scanned_January_2016_avg_daily            int64
all_scored_January_2016_avg_daily             int64
stocktwits_scanned_January_2016_avg_daily     int64
stocktwits_scored_January_2016_avg_daily      int64
twitter_scanned_January_2016_avg_daily        int64
twitter_scored_January_2016_avg_daily         int64
all_scanned_YTD_avg_monthly                   int64
all_scored_YTD_avg_monthly                    int64
stocktwits_scanned_YTD_avg_monthly            int64
stocktwits_scored_YTD_avg_monthly             int64
twitter_scanned_YTD_avg_monthly               int64
twitter_scored_YTD_avg_monthly                int64
all_scanned_2015_avg_monthly                  int64
all_scored_2015_avg_monthly                   int64
stocktwits_scanned_2015_avg_monthly           int64
stocktwits_scored_2015_avg_monthly            int64
twitter_scanned_2015_avg_monthly              int64
twitter_scored_2015_avg_monthly               int64
all_scanned_2014_avg_monthly                  int64
all_scored_2014_avg_monthly                   int64
stocktwits_scanned_2014_avg_monthly           int64
stocktwits_scored_2014_avg_monthly            int64
twitter_scanned_2014_avg_monthly              int64
twitter_scored_2014_avg_monthly               int64
all_scanned_2013_avg_monthly                  int64
all_scored_2013_avg_monthly                   int64
stocktwits_scanned_2013_avg_monthly           int64
stocktwits_scored_2013_avg_monthly            int64
twitter_scanned_2013_avg_monthly              int64
twitter_scored_2013_avg_monthly               int64
all_scanned_2012_avg_monthly                  int64
all_scored_2012_avg_monthly                   int64
stocktwits_scanned_2012_avg_monthly           int64
stocktwits_scored_2012_avg_monthly            int64
twitter_scanned_2012_avg_monthly              int64
twitter_scored_2012_avg_monthly               int64
all_scanned_2011_avg_monthly                  int64
all_scored_2011_avg_monthly                   int64
stocktwits_scanned_2011_avg_monthly           int64
stocktwits_scored_2011_avg_monthly            int64
twitter_scanned_2011_avg_monthly              int64
twitter_scored_2011_avg_monthly               int64
dtype: object

In [14]:
symbols.describe()

,all_scanned_January_2016_avg_daily,all_scored_January_2016_avg_daily,stocktwits_scanned_January_2016_avg_daily,stocktwits_scored_January_2016_avg_daily,twitter_scanned_January_2016_avg_daily,twitter_scored_January_2016_avg_daily,all_scanned_YTD_avg_monthly,all_scored_YTD_avg_monthly,stocktwits_scanned_YTD_avg_monthly,stocktwits_scored_YTD_avg_monthly,...,stocktwits_scanned_2012_avg_monthly,stocktwits_scored_2012_avg_monthly,twitter_scanned_2012_avg_monthly,twitter_scored_2012_avg_monthly,all_scanned_2011_avg_monthly,all_scored_2011_avg_monthly,stocktwits_scanned_2011_avg_monthly,stocktwits_scored_2011_avg_monthly,twitter_scanned_2011_avg_monthly,twitter_scored_2011_avg_monthly
count,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444,11444,11444,11444,...,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000,11444.000000
mean,10.797711,2.623733,2.596295,0.857917,7.971077,1.628364,0,0,0,0,...,18.762670,7.893219,68.164191,17.313352,52.076809,15.801468,9.329605,3.837207,42.524467,11.800856
std,77.531277,22.923606,30.250212,11.305452,55.201571,14.682406,0,0,0,0,...,344.342513,148.597889,626.635983,205.135724,462.841925,172.014389,126.386320,52.584767,348.485672,125.595997
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,...,0.000000,0.000000,15.000000,1.000000,2.000000,0.000000,0.000000,0.000000,2.000000,0.000000
75%,5.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0,0,0,0,...,3.000000,1.000000,35.000000,6.000000,21.000000,4.000000,2.000000,0.000000,18.000000,3.000000
max,4281.000000,1256.000000,1691.000000,590.000000,2891.000000,884.000000,0,0,0,0,...,31590.000000,13871.000000,48410.000000,14679.000000,27017.000000,9502.000000,7804.000000,3074.000000,20532.000000,8269.000000

In [ ]:
# PLOT A SAMPLE: TOTAL SCANNED MESSAGES BETWEEN 1 TO 11
# dailyData['TOTAL_SCANNED_MESSAGES'].hist(range=(1,10))
# P.show()

# the histogram of the data
plt.hist(dailyData['TOTAL_SCANNED_MESSAGES'], range=[1, 10])
plt.xlabel('Number of Daily Messages')
plt.ylabel('Total Counts')
plt.grid(True)
plt.show()

In [ ]:
# plt.show(dailyData.plot(kind = 'box'))

In [ ]:
# merge dataset left join
dailyStockSymb = merge(dailyData,symbStocks,left_on='SYMBOL',right_on = 'symbol',how = "left")

In [ ]:
dailyStockSymb = dailyStockSymb.ix[:,1:11]
dailyStockSymb.columns

In [ ]:
# Group By Stock Exchange
exchangeGrouped = dailyStockSymb.groupby(dailyStockSymb['exchange'])
sumByExchange = exchangeGrouped.sum()
print(sumByExchange.columns)
# sumByExchange

In [ ]:
# statistic description for bull bear messages ratio by exchanges
statByExchange_Ratio = exchangeGrouped['BULL_BEAR_MSG_RATIO'].describe()
statByExchange = exchangeGrouped.describe()
# export the statistic description by exchanges
statByExchange.to_csv('../data/output/statByExchange.csv', encoding='utf-8')

In [ ]:
# a table only contains the total quality of bullish, bearish and total messages for each exchange
messagesTable = sumByExchange.ix[:,[3,4,6]]
messagesTable.sort('TOTAL_SCANNED_MESSAGES', ascending=False)

In [ ]:
# the percentage of bull messages 
bullPerc = messagesTable['BULL_SCORED_MESSAGES']/messagesTable['TOTAL_SCANNED_MESSAGES']
# the percentage of bear messages
bearPerc = messagesTable['BEAR_SCORED_MESSAGES']/messagesTable['TOTAL_SCANNED_MESSAGES']

In [ ]:
# neutral = total - bull - bear
neutralCounts = messagesTable['TOTAL_SCANNED_MESSAGES']-messagesTable['BULL_SCORED_MESSAGES']-messagesTable['BEAR_SCORED_MESSAGES']
# print (neutralCounts)
neutralPerc = neutralCounts/messagesTable['TOTAL_SCANNED_MESSAGES']

In [ ]:
# check the total percentage = 1 or not
totalPerc = bullPerc + bearPerc + neutralPerc
# totalPerc

In [ ]:
# add new columns to the table. by using 'insert(idx, col_name, value)'
messagesTable.insert(2, 'NEUTRAL_SCORED_MESSAGES', neutralCounts)
# messagesTable

In [ ]:
# change data format to %
bullPerc = bullPerc.apply(lambda x: format(x, '.2%'))
bearPerc = bearPerc.apply(lambda x: format(x, '.2%'))
neutralPerc = neutralPerc.apply(lambda x: format(x, '.2%'))

In [ ]:
# sentiment summary by stock exchange
sentiOutcome = messagesTable
sentiOutcome.insert(1,'BULL_PERC', bullPerc)
sentiOutcome.insert(3,'BEAR_PERC', bearPerc)
sentiOutcome.insert(5,'NEUTRAL_PERC', neutralPerc)
# sentiOutcome

In [ ]:
# export to a csv file
sentiOutcome.to_csv('../data/output/sentimentSummaryByExchange.csv', encoding='utf-8')